[package]
name = "database"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
common.workspace = true
mongodb.workspace = true
serde.workspace = true
